// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculosContext.Vehiculos;

namespace VehiculosContext.Migrations
{
    [DbContext(typeof(VehiculoContext))]
    partial class VehiculoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VehiculoEntity.MarcaVehiculo", b =>
                {
                    b.Property<int>("MarcaVehiculoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaVehiculoID");

                    b.ToTable("MarcaVehiculos");
                });

            modelBuilder.Entity("VehiculoEntity.ModeloVehiculo", b =>
                {
                    b.Property<int>("ModeloVehiculoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MarcaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloVehiculoID");

                    b.ToTable("ModeloVehiculos");
                });

            modelBuilder.Entity("VehiculoEntity.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ruedas")
                        .HasColumnType("int");

                    b.HasKey("TipoVehiculoID");

                    b.ToTable("TipoVehiculos");
                });

            modelBuilder.Entity("VehiculoEntity.Vehiculo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Chasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kms")
                        .HasColumnType("int");

                    b.Property<int>("MarcaVehiculoID")
                        .HasColumnType("int");

                    b.Property<int>("ModeloVehiculoID")
                        .HasColumnType("int");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoVehiculoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
